import { nanoid } from "nanoid";

/**
 * This "singleton" ID-service provides unique IDs to the app.
 * All IDs are strings with a length of 6 symbols (for demonstration purpose).
 *
 * Note: this service is "data agnostic" and may be used "globally"!
 * - It does not know about any data, that may be associated with any given ID.
 * - It allows providing unique IDs for different data structures i.e. object types concurrently.
 */
class IDService {
  /**
   * This is a "in-memory" storage for all the generated, unique IDs.
   *
   * !!! REPLACE THIS TRANSIENT STORAGE WITH A PERSISTING ONE FOR PRODUCTION USE !!!
   */
  private readonly IDS = new Set<string>();

  /**
   * Generate a unique ID.
   *
   * @returns a new unique ID string made of 6 symbols(chars)
   */
  generateId(): string {
    let newID: string = "";
    while (true) {
      newID = nanoid(6);
      if (this.inUse(newID)) {
        newID = ""; // loop if the ID is already in use
      }
      else {
        this.IDS.add(newID); // add the ID to the list of used IDs and break the loop
        break;
      }
    }
    return newID;
  }

  /**
   * Remove an ID from the consumed IDs i.e. from the list of already
   * generated IDs.
   *
   * This make it possible to lookup for "ID in use" without knowledge
   * of the real Data associated with the ID.
   *
   * Note: once removed from the list, an ID cannot be re-inserted but
   * randomly generated by the generateID function (unlikely).
   *
   * @param id a unique ID string
   */
  removeId(id: string): void {
    this.IDS.delete(id);
  }

  /**
   * Reset the full list of IDs "already in use".
   *
   * Note: once removed, the IDs cannot be re-inserted but
   * randomly generated by the generateID function (unlikely).
   */
  reset(): void {
    this.IDS.clear();
  }

  /**
   * Check if a given ID is "in use"
   *
   * @param id ID to be checked against the list of all generated IDs.
   * @returns true if the ID is already in use, false otherwise.
   */

  inUse(id: string): boolean {
    return this.IDS.has(id);
  }
}

/**
 * ES6 Module Singleton Pattern
 */
export default new IDService();
