import winston from "winston";
import { env } from "./environment";

const { combine, timestamp, printf, colorize, json, uncolorize, splat } = winston.format;
const OneMB = 1024 * 1024;

/**
 * Default, configurable application wide logger engine to
 * output/export logs in the console and in a log file,
 */
const Logger = winston.createLogger({
  levels: winston.config.npm.levels,
  exitOnError: !env.NODE_TEST,
  level: env.LOG_LEVEL ?? (env.NODE_DEV ? "debug" : "http"),
  transports: [
    new winston.transports.Console({
      format: combine(
        colorize(),
        timestamp(),
        splat(),
        printf(info => `[${info.timestamp}]${info.label ? `[${info.label}]` : ""} ${info.level} ${info.message}`),
      ),
    }),
    new winston.transports.File({
      filename: env.LOG_FILE,
      maxsize: OneMB,
      maxFiles: 1,
      tailable: true,
      format: combine(
        splat(),
        timestamp(),
        uncolorize(),
        json({ space: !env.NODE_DEV ? 0 : 2 }),
      ),
    }),
  ],
});

/**
 * Retrieve an application-logger as provided by winston.
 * @param label when provided, the label is displayed/saved in the log-payload generated by the returned logger instance.
 * @returns the global instance of the winston logger or a child instance of the global logger (when a label is provided).
 */
export default function logger(label: string = ""): winston.Logger {
  return label ? Logger.child({ label }) : Logger;
}
