import path, { dirname } from "node:path";
import winston from "winston";
import { env } from "./environment";

const { combine, timestamp, printf, colorize, json, uncolorize, splat, errors } = winston.format;
const OneMB = 1024 * 1024;

/**
 * Generate a message-part out of the winston info object with regard to the environment and error context.
 * @param info the info object as provided by winston within a format callback
 * @returns a formated message
 */
function formatConsoleInfoMessage(info: winston.Logform.TransformableInfo): string {
  const errStack = env.NODE_DEV && info.stack ? `\n${info.stack}\n` : "";
  const name = (info.statuscode ? info.statuscode : info.name);
  const logIdentifier = name ? `${name} ` : "";
  return `${logIdentifier}${info.message}${errStack}`;
}

const unhandledExceptionLogFile = path.join(dirname(env.LOG_FILE), "unhandled-exceptions.log");
const unhandledRejectionsLogFile = path.join(dirname(env.LOG_FILE), "unhandled-rejections.log");

/**
 * Default, configurable application wide logger engine to
 * output/export logs in the console and in log files.
 * The logger also handles uncaught exceptions and rejections.
 */
const Logger = winston.createLogger({
  levels: winston.config.npm.levels,
  exitOnError: !env.NODE_TEST,
  level: env.LOG_LEVEL ?? (env.NODE_DEV ? "debug" : "http"),
  format: combine(errors({ stack: true }), json({ space: !env.NODE_DEV ? 0 : 2 })), // IMPORTANT - "errors(...)" AND "json(...)" MUST BE CALLED OUTSIDE OF THE TRANSPORT FORMAT-CALLBACKS BELOW
  transports: [
    new winston.transports.Console({
      format: combine(colorize(), timestamp(), splat(), printf(info => `[${info.timestamp}]${info.label ? `[${info.label}]` : ""} ${info.level} ${formatConsoleInfoMessage(info)}`)),
    }),
    new winston.transports.File({
      filename: env.LOG_FILE,
      maxsize: OneMB,
      maxFiles: 1,
      tailable: true,
      format: combine(splat(), timestamp(), uncolorize(), json({ space: !env.NODE_DEV ? 0 : 2 })),
    }),
  ],
  exceptionHandlers: [
    new winston.transports.File({ filename: unhandledExceptionLogFile }),
  ],
  rejectionHandlers: [
    new winston.transports.File({ filename: unhandledRejectionsLogFile }),
  ],
});

/**
 * Retrieve an application-logger as provided by winston.
 * @param label when provided, the label is displayed/saved in the log-payload generated by the returned logger instance.
 * @returns the global instance of the winston logger or a child instance of the global logger (when a label is provided).
 */
export default function logger(label: string = ""): winston.Logger {
  return label ? Logger.child({ label }) : Logger;
}
