import winston from "winston";
import { env } from "./environment";

const { combine, timestamp, printf, colorize, json, uncolorize, splat, errors } = winston.format;
const OneMB = 1024 * 1024;

/**
 * Generate a message-part out of the winston info object with regard to the environment and error context.
 * @param info the info object as provided by winston within a format callback
 * @returns a formated message
 */
function formatConsoleInfoMessage(info: winston.Logform.TransformableInfo): string {
  return (env.NODE_DEV && info.stack) ? `${info.stack}` : info.name ? `${info.name} ${info.message}` : `${info.message}`;
}

/**
 * Default, configurable application wide logger engine to
 * output/export logs in the console and in a log file,
 */
const Logger = winston.createLogger({
  levels: winston.config.npm.levels,
  // exitOnError: !env.NODE_TEST,
  level: env.LOG_LEVEL ?? (env.NODE_DEV ? "debug" : "http"),
  format: combine(errors({ stack: true })), // IMPORTANT - "errors(...)"" MUST BE CALLED OUTSIDE OF THE TRANSPORT FORMAT-CALLBACKS BELOW
  transports: [
    new winston.transports.Console({
      format: combine(
        colorize(),
        timestamp(),
        splat(),
        printf(info => `[${info.timestamp}]${info.label ? `[${info.label}]` : ""} ${info.level} ${formatConsoleInfoMessage(info)}`),
      ),
    }),
    new winston.transports.File({
      filename: env.LOG_FILE,
      maxsize: OneMB,
      maxFiles: 1,
      tailable: true,
      format: combine(
        splat(),
        timestamp(),
        uncolorize(),
        json({ space: !env.NODE_DEV ? 0 : 2 }),
      ),
    }),
  ],
});

/**
 * Retrieve an application-logger as provided by winston.
 * @param label when provided, the label is displayed/saved in the log-payload generated by the returned logger instance.
 * @returns the global instance of the winston logger or a child instance of the global logger (when a label is provided).
 */
export default function logger(label: string = ""): winston.Logger {
  return label ? Logger.child({ label }) : Logger;
}
