/**
 * Shared/common zod-schema definitions
 */
import z from "zod";

const LAN = z.string().nonempty().regex(/^(https?:\/\/)(?:localhost|127.0.0.1|0.0.0.0|192.168.\d{1,3}.\d{1,3})$/, "Invalid input: expected a protocol + LAN address");
const WAN = z.url({ protocol: /^https?$/, hostname: z.regexes.domain, error: "Invalid input: expected a protocol + WAN host/domain name" });

export const LAN_OR_WAN = z.union([WAN, LAN], "Invalid input: expected an URL (protocol + LAN or WAN hostname/IP)").meta({ id: "LAN_OR_WAN" }); ;
export const FILEEXT_LOG = z.stringFormat("LOG-FILE-NAME", /[^/]+\.log$/i, "Invalid input: log-file name must end with '.log'");
export const RequestParamId = z.string().normalize().trim().length(6).nonempty().nonoptional(); // as generated by the id-service
export const Sort = { asc: "asc", desc: "desc" } as const;
export const QuerySort = z.enum(Sort, "Invalid 'sort' query option: expected one of 'asc' or 'desc'")
  .optional()
  .meta({ param: { id: "QuerySort", name: "sort", in: "query" }, description: "sort the list ascending or descending" });

export const QueryPage = z.coerce.number()
  .int()
  .min(1)
  .max(1000) // arbitrary page-max value
  .positive("Invalid 'page' query option: expected a positive integer")
  .optional()
  .meta({ param: { id: "QueryPage", name: "page", in: "query" }, description: "return the list starting at a given page - related to the 'limit' parameter" });

export const QueryLimit = z.enum(["10", "25", "50", "100"], "Invalid 'limit' query option: expected one of '10', '25', '50' or '100'")
  .pipe(z.coerce.number())
  .optional()
  .meta({ param: { id: "QueryLimit", name: "limit", in: "query" }, description: "limit the amount of items returned and/or define the size of a page - related to the 'page' parameter" });

// Just an example -> this schema should comply with the id-generator format for new IDs
export const IdSchema = z.string().length(6);

export const ClientErrorSchema = z.object({
  status: z.literal("error"),
  statuscode: z.number().int().min(400).max(499).nonoptional(),
  message: z.string().nonempty().nonoptional(),
}).meta({ id: "ClientError", description: "Client request error" });

export const ClientErrorBadRequestSchema = z.object({
  ...ClientErrorSchema.shape, // merge shapes - better than with ClientErrorSchema.extend(...)
  statuscode: z.literal(400),
  formErrors: z.array(z.string()).meta({ description: "Request Validation: The 'formErrors' array contains details on any top-level errors e.g. about unrecognized keys/properties." }),
  fieldErrors: z.record(z.string(), z.array(z.string())).meta({ description: "Request Validation: The 'fieldErrors' object provides an array of errors for each invalid field in the schema." }),
}).meta({ id: "ClientErrorBadRequest", description: "Client request error" });

export const ServerErrorSchema = z.object({
  status: z.literal("error").meta({ example: "error" }),
  statuscode: z.number().int().min(500).max(599).nonoptional().meta({ example: "500" }),
  message: z.string().nonempty().nonoptional().meta({ example: "An unexpected server error occured" }),
}).meta({ id: "ServerError", description: "Unexpected server error" });

export const GetAllRequestQuerySchema = z.object({
  sort: QuerySort,
  page: QueryPage,
  limit: QueryLimit,
});
