/**
 * Shared/common zod-schema definitions
 */
import z from "zod";

const LAN = z.string().nonempty().regex(/^(https?:\/\/)(?:localhost|127.0.0.1|0.0.0.0|192.168.\d{1,3}.\d{1,3})$/, "Invalid input: expected a protocol + LAN address");
const WAN = z.url({ protocol: /^https?$/, hostname: z.regexes.domain, error: "Invalid input: expected a protocol + WAN host/domain name" });

export const LAN_OR_WAN = z.union([WAN, LAN], "Invalid input: expected an URL (protocol + LAN or WAN hostname/IP)");
export const FILEEXT_LOG = z.stringFormat("LOG-FILE-NAME", /[^/]+\.log$/i, "Invalid input: log-file name must end with '.log'");
export const RequestParamId = z.string().normalize().trim().length(6).nonempty().nonoptional(); // as generated by the id-service
export const Sort = { asc: "asc", desc: "desc" } as const;
export const QuerySort = z.enum(Sort, "Invalid 'sort' query option: expected one of 'asc' or 'desc'").optional();
export const QueryPage = z.coerce.number().int().positive("Invalid 'page' query option: expected a positive integer").optional();
export const QueryLimit = z.enum(["10", "25", "50", "100"], "Invalid 'limit' query option: expected one of '10', '25', '50' or '100'").pipe(z.coerce.number()).optional();
