# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# |                                                           |
# |    This "REST client simulation" requires the VSCode      |
# |    extension "REST Client" as provided here:              |
# |                                                           |
# |    https://github.com/Huachao/vscode-restclient.git       |
# |                                                           |
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

@hostname = {{$dotenv HOST}}
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}
@contentType = application/json

// =======================================================
// # DEMO ENDPOINTS                                      #
// =======================================================

### Simple Endpoint
GET {{host}}

### DISCLOSE (!) the server environemnt
GET {{host}}/environment


### Simulate server "logs" to console/file
GET {{host}}/simulations/logs


### Simulate server "catch-all" for unhandled exceptions
GET {{host}}/simulations/exception

### Simulate server "catch-all" for unhandled rejection [TERMINATING SERVER PROCESS]
GET {{host}}/simulations/rejection


// =======================================================
// # URL-SHORTENER ENDPOINT                              #
// =======================================================

### URL-Shortener - GetAll
GET {{host}}/shortener

### URL-Shortener - GetOne
GET {{host}}/shortener/1lbIMh

### URL-Shortener - Create
POST {{host}}/shortener
Content-Type: application/json

{
  "url": "https://github.com/khatastroffik"
}
