# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# |                                                           |
# |    This "REST client simulation" requires the VSCode      |
# |    extension "REST Client" as provided here:              |
# |                                                           |
# |    https://github.com/Huachao/vscode-restclient.git       |
# |                                                           |
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

@hostname = {{$dotenv HOST}}
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}
@contentType = application/json

// =======================================================
// # DEMO ENDPOINTS                                      #
// =======================================================

### Simple Endpoint - [200] OK
GET {{host}}

### DISCLOSE (!) the server environemnt - [200] OK
GET {{host}}/environment

### Simulate error "logs" to console/file  - [200] OK
GET {{host}}/simulations/logs

### Simulate server "catch-all" for unhandled exceptions - [418] I'm a Teapot
GET {{host}}/simulations/exception

### Simulate server "catch-all" for unhandled rejection [!!! TERMINATING SERVER PROCESS !!!]
GET {{host}}/simulations/rejection


// =======================================================
// # URL-SHORTENER ENDPOINT                              #
// =======================================================

### URL-Shortener - GetAll - [200] OK
GET {{host}}/shortener

### URL-Shortener - GetOne - [200] OK
GET {{host}}/shortener/testid

### URL-Shortener - GetOne - [404] Not Found
GET {{host}}/shortener/BAD_ID

### URL-Shortener - GetOne - [400] Bad Request (too big)
GET {{host}}/shortener/ID_TOO_LONG

### URL-Shortener - Create - [201] Created
POST {{host}}/shortener
Content-Type: application/json

{
  "url": "https://github.com/khatastroffik"
}

### URL-Shortener - Create  - [400] Bad Request (invalid input)
POST {{host}}/shortener
Content-Type: application/json

{
  "url": "not a valid value"
}

### URL-Shortener - Create  - [400] Bad Request (Unknown properties)
POST {{host}}/shortener
Content-Type: application/json

{
  "url": "https://github.com/khatastroffik",
  "unknown-property": "should not be there"
}
